name: Warehouse CMS CI/CD

on:
  push:
    branches: ['dbconnection']
  pull_request:
    branches: ['dbconnection']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Only deploy on pushes to dbconnection branch
    if: github.ref == 'refs/heads/dbconnection' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'warehouse-cms' # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}/myapp

      # Optional: Create migration script if needed
      - name: Generate Migration Script
        run: |
          dotnet tool install --global dotnet-ef
          dotnet ef migrations script --idempotent -o ${{env.DOTNET_ROOT}}/migration.sql
        env:
          ASPNETCORE_ENVIRONMENT: Production
